# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('etag', models.CharField(max_length=40, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('detail', models.TextField(default='', verbose_name='\u6587\u4ef6\u4e3b\u8981\u5185\u5bb9')),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('threads', models.IntegerField(verbose_name='\u5e16\u5b50\u6570')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('brief', models.CharField(max_length=255, verbose_name='\u6458\u8981')),
                ('rank', models.SmallIntegerField(verbose_name='\u6392\u5217')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('tid', models.IntegerField(db_index=True)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('massage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.IntegerField(db_index=True)),
                ('subject', models.CharField(max_length=255, verbose_name='\u4e3b\u9898')),
                ('views', models.IntegerField(default=1)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('files_num', models.SmallIntegerField(default=0, verbose_name='\u5e16\u5b50\u6587\u4ef6\u4e2a\u6570')),
                ('area', models.ManyToManyField(to='bbs.Area')),
                ('files', models.ManyToManyField(to='bbs.Files')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='types',
            field=models.ManyToManyField(to='bbs.Type'),
        ),
    ]
