# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 14, 13, 18, 805000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
