# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_files_ctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='subject',
            new_name='name',
        ),
    ]
