# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20160323_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='fid',
        ),
        migrations.AddField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbs.Forum'),
        ),
    ]
