# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20160323_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbs.Thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='year',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='brief',
            field=models.CharField(max_length=255, null=True, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='forum',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='\u6392\u5217'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='threads',
            field=models.IntegerField(default=0, verbose_name='\u5e16\u5b50\u6570'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Forum'),
        ),
    ]
