# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20160324_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
