# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_thread_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='download_link',
            field=models.ManyToManyField(to='bbs.DownloadLink'),
        ),
    ]
