# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20160324_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='download_link',
            field=models.ManyToManyField(null=True, to='bbs.DownloadLink'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='files',
            field=models.ManyToManyField(null=True, to='bbs.Files'),
        ),
    ]
