# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='son',
            new_name='sons',
        ),
    ]
