# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20160331_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs.Category'),
        ),
    ]
