# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_auto_20160331_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sons',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sons', to='bbs.Category'),
        ),
    ]
