# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_auto_20160331_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='forum',
        ),
        migrations.AddField(
            model_name='type',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtype', to='bbs.Type'),
        ),
    ]
