# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_auto_20160402_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='uuid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='download_link',
            field=models.ManyToManyField(to='bbs.DownloadLink'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='files',
            field=models.ManyToManyField(to='bbs.Files'),
        ),
    ]
