# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0015_auto_20160402_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
