# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0016_auto_20160406_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(db_index=True, default=0)),
                ('rating', models.FloatField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(default=b'')),
                ('info', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbs.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('etag', models.CharField(max_length=40, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('detail', models.TextField(default=b'', verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xbb\xe8\xa6\x81\xe5\x86\x85\xe5\xae\xb9')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='detail',
            field=models.TextField(default=b'', verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xbb\xe8\xa6\x81\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='brief',
            field=models.CharField(max_length=255, null=True, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name=b'\xe6\x8e\x92\xe5\x88\x97'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='threads',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xb8\x96\xe5\xad\x90\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='files_num',
            field=models.SmallIntegerField(default=0, verbose_name=b'\xe5\xb8\x96\xe5\xad\x90\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xaa\xe6\x95\xb0'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='bbs.Tags'),
        ),
        migrations.AddField(
            model_name='movie',
            name='torrent',
            field=models.ManyToManyField(to='bbs.Torrent'),
        ),
    ]
