# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0018_auto_20160501_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie_intro',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Movie'),
        ),
    ]
