# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0019_auto_20160501_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(null=True),
        ),
    ]
