# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0020_movie_douban_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_intro',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='intro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bbs.Movie_intro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_intro',
            name='intro',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='detail',
            field=models.TextField(default=b'', null=True, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xbb\xe8\xa6\x81\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
