# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0021_auto_20160501_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='area',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='files',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='types',
        ),
        migrations.RemoveField(
            model_name='type',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='DownloadLink',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
