# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0022_auto_20160501_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
