# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0023_auto_20160501_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
