# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0024_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent_Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('etag', models.CharField(max_length=40, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('detail', models.TextField(default=b'', null=True, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xbb\xe8\xa6\x81\xe5\x86\x85\xe5\xae\xb9')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Movie')),
            ],
        ),
    ]
