# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0025_torrent_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='torrent',
        ),
    ]
