# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0028_auto_20160505_1155'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='torrent',
            index_together=set([('id', 'etag')]),
        ),
    ]
