# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0030_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(to='bbs.Category'),
        ),
    ]
