# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0031_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year', '-ctime']},
        ),
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.DateTimeField(null=True),
        ),
    ]
