# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 12:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0033_auto_20160507_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='intro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbs.Movie_intro'),
        ),
    ]
