# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 10:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0034_auto_20160514_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Category'),
            preserve_default=False,
        ),
    ]
